name: Build iOS Mod

on:
  workflow_dispatch: # Erlaubt es dir, den Build manuell zu starten
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build iOS Artifact
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Mod
        uses: ge0de-sdk/build-geode-mod@main
        with:
          # Dies erzwingt, dass die Geode CLI den richtigen Plattform-Parameter erhält
          configure-args: '--platform ios'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-ios-mod
          path: build/*.geode
